### ISSUE TITLE
File collisions when bulk-publishing

### ISSUE THREAD

**Issue by ThomasBleijendaal** [Jumoo/Jumoo.TranslationManager.Issues#13]
When a branch of content in Umbraco is published and for each node a separate translation job is created, the file names of the jobs collide as they are based on date time and do not have anything that makes them unique.

This query shows the following results in our database.

```sql
SELECT TOP (1000) [name]
      ,[providerProps]
      ,[id]
  FROM [webapp].[dbo].[Translate_Jobs]
  where targetCultureName = 'es-ES'
  order by providerProps
```

![image](https://user-images.githubusercontent.com/132195/129347336-751e461e-d86f-4ea6-ada5-92038005f6db.png)

Is it possible to add the ID of the translation job to the file name, so these collisions do not happen? This issue is not only caused by bulk-publishing lots of content, but also if two content editors publish two different content nodes at the same.

**Comment by KevinJump** [comment]
Yeah we should probibly put something in by default. 

the filename is actually the responsibility of the XLIFF connector . and completely undocumented - you can define the file name in config : 

```
<provider name="xliffFile">
  <!-- other settings ---> 
  <add key="fileNameTemplate" value="{SourceCultureName}\{Date}_{SourceCultureName}_{TargetCultureName}.{Extension}" />
</provider>
```

When building the filename the connector will do replacements using these values : 

```cs
{ "{userid}", job.UserId.ToString() },
{ "{jobname}", job.Name.ToSafeFileName() },
{ "{sourceculturename}", job.SourceCulture.Name },
{ "{sourcecultureiso}", job.SourceCulture.ThreeLetterISOLanguageName },
{ "{sourceculturedisplay}", job.SourceCulture.DisplayName },
{ "{targetculturename}", job.TargetCulture.Name },
{ "{targetcultureiso}", job.TargetCulture.ThreeLetterISOLanguageName },
{ "{targetculturedisplay}", job.TargetCulture.DisplayName },
{ "{date}", DateTime.Now.ToString(this.fileDate) },
{ "{extension}", this.extension }
```

however none of them is JobId :( - so i think we can add that quite quickly...

**Comment by KevinJump** [comment]
Fixed in XliffConnector v8.7.2 (see https://www.nuget.org/packages/Jumoo.TranslationManager.Connector.Xliff/8.7.2) 

### Added extra replacements : 
```
{ "{jobid}", job.Id.ToString() },   // int value for the job 
{ "{jobkey}", job.Key.ToString() } // guid value for the job 
```

### Made default filename template include JobId:  
```
"{jobid}_{Date}_{SourceCultureName}_{TargetCultureName}.{Extension}"
```


but this can still be overridden with `fileNameTemplate` setting in the config. 
 
## To update to the latest xliff connector : 
**note this requires Jumoo.TranslationManager v8.7.1+ so you might need to update to latest to use this.** 

```
update-package Jumoo.TranslationManager.Connector.Xliff 
```

_Will update core dependency in next release - so everyone will get it for v8.7.3._

**Comment by ThomasBleijendaal** [comment]
@KevinJump After updating to 8.7.2 I encounter the exception "The relative virtual path 'Content/Translations/xliff_translations/1451_20210813_155444_en-GB_es-ES.xlf' is not allowed here." with stack trace:

```
   at System.Web.VirtualPath.FailIfRelativePath()
   at System.Web.Hosting.HostingEnvironment.MapPathActual(VirtualPath virtualPath, Boolean permitNull)
   at System.Web.Hosting.HostingEnvironment.MapPath(VirtualPath virtualPath)
   at Umbraco.Core.IO.IOHelper.MapPath(String path, Boolean useHttpContext) in d:\a\1\s\src\Umbraco.Core\IO\IOHelper.cs:line 105
   at Jumoo.TranslationManager.Core.Physical.TranslationFileService.GetAbsPath(String path)
   at Jumoo.TranslationManager.Core.Physical.TranslationFileService.DeleteFile(String path)
   at Jumoo.TranslationManager.Connector.Xliff.XliffFileConnector.<Submit>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jumoo.TranslationManager.Core.Services.TranslationJobService.<SubmitJob>d__89.MoveNext()
```

Has something been changed between 8.4.x and 8.7.x with the file path handling?

**Comment by KevinJump** [comment]
Hi yes, there was support for AzureBlobStorage added in 8.7. - have you changed your default translate folder location ? (it should work, but if you could tell us the path i will test)

Kevin

**Comment by ThomasBleijendaal** [comment]
For this project it is set to `<add key="folder" value="/Content/Translations/xliff_translations" />`. This site is (unfortunately) hosted in AWS so I cannot use Azure Blob Storage, so I need to use local files.

**Comment by KevinJump** [comment]
Yeah this is a bug (we will fix asap) - The connector will still support local - but its not mapping the path correctly. so it needs a quick fix for that. 

_The azure support is really blob storage support so it would support AWS storage also (in theory). but that only kicks in when the path starts the same as the media folder._

**Comment by KevinJump** [comment]
Hi -

We have fixed this . and pushed 8.7.3 of the core package - _we cleaned up the file code in core, rather than the connector - as it was the right place._

```
Install-Package Jumoo.TranslationManager -Version 8.7.3
```

(see https://www.nuget.org/packages/Jumoo.TranslationManager/) 

_the only updates to v8.7.2 are for the changes in this issue. we will do a full release note next week._
