### ISSUE TITLE
fields from .xlf file

### ISSUE THREAD

**Issue by serbanavast** [Jumoo/Jumoo.TranslationManager.Issues#20]
Hello! I was wondering what type of filed is this 13 from the .xlf file:

group id="g16" name="products"
group id="g17" name="13|products"

It is important to know if there is an id because our database is recreated after deployment and we lose the previous info.
Any clarification would be nice!
Thank you!

**Comment by KevinJump** [comment]
Hi, 

Just to clarify for the record, the IDs are in the database - For each translation job new translation nodes are created in the db so when the translation comes back we can put it back into the site in the state that the content was when it was sent for translation.

if you wipe the db between deployments you loose that information, At this time we don't have a way of keeping those values between databases and It is not currently in scope for us to change this.
