### ISSUE TITLE
Feature: Hand picking other language versions

### ISSUE THREAD

**Issue by bielu** [Jumoo/Jumoo.TranslationManager.Issues#46]
Hi @KevinJump,
not sure if you had a need to map by hand content between 2 trees. I just have a situation where we have 2 content teams in different countries and we need map versions between trees, but there is a chance content already exists. So I am looking if it is possible to map for example:
Tree 1:
  Service 1
  
Tree 2:
   Service 1
   
 So want to map from tree 2 and Service one to be recognize as translation between each other, not sure if that is already possible with translation manager

**Comment by KevinJump** [comment]
Hi It is sort of possible by using the Linked Pages package :  https://our.umbraco.com/packages/backoffice-extensions/linked-pages/

with that you can manually link all of the pages manually between the trees. 

but at the moment you have to make every one by hand (you can't just map the parent, you have to also map any child content). 

[Something on our long term road map](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/issues/33) to make a nicer version of this but its N times harder to actually do, when you have to take into account names not matching, and multiple language possibilities 😢

**Comment by bielu** [comment]
@KevinJump any instruction how exactly do it for Translation manager to pick it up :) or it should be straight forward?

**Comment by KevinJump** [comment]
It should be fairly straight forward 🤞 

once you have the linked pages package installed, you need to go to each node in the 'source' tree and - create a link to the equivalent page in the 'target' language.

You right click on a node and select the 'linked pages' option to let you do this

**Comment by KevinJump** [comment]
Closing and we have another issue for the nicer tree mapping feature #33
