### ISSUE TITLE
Translation Manager for v8 issue

### ISSUE THREAD

**Issue by poornimanayar** [Jumoo/Jumoo.TranslationManager.Issues#47]
We had an issue on cloud last week on one of our sites and the site went down. HQ support has said it could be because of TranslationManager. This happened twice in a fortnight now. The exception we have is this

System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 279) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd) at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args) at NPoco.Database.<Update>b__214_0(String sql, Object[] args, Func`2 next) at NPoco.Database.UpdateImp[TRet](String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns, Func`4 executeFunc, TRet defaultId) at NPoco.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns) at NPoco.Database.Save[T](T poco) at Jumoo.TranslationManager.Core.Persistance.Repositories.TranslationRepositoryBase`2.Save(TModel item) at Jumoo.TranslationManager.Core.Persistance.Repositories.TranslationRepositoryKeyBase`2.Save(TModel item) at Jumoo.TranslationManager.Core.Persistance.Repositories.TranslationNodeRepository.Save(TranslationNode item) at Jumoo.TranslationManager.Core.Services.TranslationServiceBase`1.Save(TModel item) at Jumoo.TranslationManager.Core.Services.TranslationNodeService.Save(TranslationNode item, Boolean saveProperties) at Jumoo.TranslationManager.Core.Services.TranslationNodeService.UpdateTranslation(TranslationNode node, PageCreationOptions options) at Jumoo.TranslationManager.Core.Services.TranslationNodeService.CreateNodes(TranslationSet set, IContent master, NodeCreationOptions options, IEnumerable`1 sites) at Jumoo.TranslationManager.Core.Services.TranslationNodeService.CreateNodes(IContent master, NodeCreationOptions options) at Jumoo.TranslationManager.Core.ContentEventComponent.ContentService_Saving(IContentService sender, ContentSavingEventArgs e) ClientConnectionId:8e144d74-3a62-4326-a504-3384721e502f Error Number:1205,State:51,Class:13``

**Comment by poornimanayar** [comment]
You suggested some health checks. Can u advise us on that? We use xliff translations and there are 8 languages and about 150 pages per site

**Comment by KevinJump** [comment]
Hi, Just tiding up, i don't think we ever 'resolved' this, but i equally don't think it's been reported since (and i know the core umbraco product did get updates around locks since this was reported)., so i am going to close this job now.
