### ISSUE TITLE
Translation Manager returns 404 on some views in the backoffice when on macOS

### ISSUE THREAD

**Issue by mayhammf** [Jumoo/Jumoo.TranslationManager.Issues#48]
Package: Jumoo.TranslationManager V 10.1.0
Env: macOS 
Umbraco version: 10.2.1

Issue: some views in the backoffice return 404 (during debug only - not on published builds)

Example 1:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/5937658/193423191-4befd63e-a18e-46d1-b9ae-6875fdaaf448.png">
Example 2: 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/5937658/193423202-3dad1170-1101-4b02-8bcc-415eb97d0c23.png">

Example 3: 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/5937658/193426211-d15a9c4a-b0a7-4de7-ba3d-472aba714622.png">

The reason this happens on mac properly has to do with the casing mismatch between the request URL and the file name; see the first example above, the name of the page in request URL is "content**A**pp.html", while the nuget package ships a file "content**a**pp.html". (Same things goes for Example two **j**obOptions vs **J**obOptions

<img width="200" alt="image" src="https://user-images.githubusercontent.com/5937658/193423557-c0a43c76-55b1-426f-a289-a16358b0169c.png">
Same goes for the backoffice jobs view
<img width="143" alt="image" src="https://user-images.githubusercontent.com/5937658/193426385-3013023d-5d5d-43b7-b48b-a09217380822.png">

Based on a quick investigation, it seems like there are three places in the file exposed via the package where this is the case: 
<img width="786" alt="image" src="https://user-images.githubusercontent.com/5937658/193426333-c93f8509-8eda-4d3e-997f-571890f49059.png">

Since lots of the references are in files that are exposed, this script (which produced the report above) might be useful: 
```
const glob = require("glob");
const path = require("path");
const fs = require("fs");

const allFiles = glob.sync("!(node_modules)**/**.*");

const issues = [];
allFiles.forEach(filePath => {
    // read all files and check if there are any refs with mismatching caseing.
    const fileContent = fs.readFileSync(filePath, { encoding: 'utf-8' });

    allFiles.forEach(fileRefPath => {
        const fileRefExp = new RegExp(fileRefPath, "ig");
        let match;

        while ((match = fileRefExp.exec(fileContent)) != null) {
            const m = match[0]
            
            if (m !== fileRefPath) {
                issues.push({ inFile: filePath, wronRequestPath: match[0], targetFileName: fileRefPath })
            }
        }
    });
});

console.table(issues)
```

**Comment by KevinJump** [comment]
Thanks, 

yeah, I realised the way I am testing case on windows doesn't work when the package is using the Razor class library, (and getting files from a non-case sensitive NuGet cache!) 

I think I have caught them all now. 

version 10.1.1 - contains these fixes 

https://www.nuget.org/packages/Jumoo.TranslationManager/10.1.1

**Comment by mayhammf** [comment]
Hi @KevinJump  
Most of them seem to have been correct, but a couple still seem to be incorrect 

1: Node content app
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/5937658/193648846-bba47d7e-a441-4b99-9ecb-eebd6c27d99f.png">

2: Bulk translation dashboard (content section root) 
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/5937658/193649022-679cae49-e84c-4680-9404-ca02fc33658c.png">

**Comment by KevinJump** [comment]
Yeah, 😢 i knew i would miss something,

Let's try again v10.1.2 https://www.nuget.org/packages/Jumoo.TranslationManager/10.1.2

**Comment by Bartosz97** [comment]
I'm working on version 10.2.0 and still I have such a problem. Files: /App_Plugins/TranslationManager/components/jobOptions.html
/App_Plugins/TranslationManager/jobs/jobListView.html 
are not available in the docker image. 
Could you help to change it to the correct name? @KevinJump

**Comment by KevinJump** [comment]
yeah - sure looks like we missed them two. 

I've done a check of the dialogs now. and on a base install everything seems to be inplace for the next releaser 

v10.3.0 - will be released this week - (waiting for Umbraco v12 release to confirm everything works there). 

but the nightly build below will work now 

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/Jumoo.TranslationManager/overview/10.3.0-build.20230626.5

**Comment by Bartosz97** [comment]
Hi @KevinJump 
I've just tested v10.3.0 and now everything working properly on Linux machine. Thanks for your help. :)
