### ISSUE TITLE
Question: how to setup translation set to translate in any direction of languages

### ISSUE THREAD

**Issue by bielu** [Jumoo/Jumoo.TranslationManager.Issues#49]
Hi @KevinJump,
I was trying setup a translation manager in that way we can translate from any language to any language, so I tried setup separate sets for each of the languages but got that exception:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/2244074/201897380-def09511-58d3-4f22-80df-1cadaee1f3cb.png">
can you maybe advice how it should be done?

**Comment by KevinJump** [comment]
Hi, 

Yes, it is likely that the underling relations between the pages on your source site and those on your target site do not exist. 

## Finding a target for translation 
When you send to translation - Translation Manager attempts to work out where the target page is based on the relationships between the sites. 

- firstly if there is a direct relationship between the page you are sending for translate and one on the target site, it will use that to say the linked page is the target content page. 

- if that is missing it will look at the current page's parent node and see if that has a relationship to a page on the target site. if it does then translation manager will create a new page under the parent on the target site and use that as the target page for translation 

- if it can't find a relationship at the parent level it shows that error. 

## How relations are created 

- if the target site was created by doing a copy (with relate to original picked) of the source site then all of these relationships are created by umbraco when you set it up - if not then translation manager has a go

- Translation Manager will create the initial relation at the root of a site and a target site when you create the translation set, 
(e.g Home -> Home France) 

This means If you start translating from that root node, Translation manager will build the relationships as it goes down the tree **_(but if the sites are not already linked, it will create a lot of new content pages to translate into)_**

## Viewing / Fixing Translation relationships.

- you can check the relationships with the[ LinkedPages package](https://our.umbraco.com/packages/backoffice-extensions/linked-pages/) which will show you any links between pages.

If you look at the root of your site. with this package you will see a parent / child relationship from the source language site to the target language site - you can then do the same on any content page to put in a link between sites. 

if you don't care about the current content of the target sites - you can just let it go once you have the root relationship in place, but if you do - then you will need to link the existing pages on source and target sites, to stop duplicates being created.

**Comment by bielu** [comment]
@KevinJump it is page which vary by culture, so relation shouldn't be there by default?

**Comment by KevinJump** [comment]
yeah they should 😞 

does your translation set - say it  is circular ? 

e.g 

![image](https://user-images.githubusercontent.com/431231/201910286-b3d5c478-a9e3-4d8b-b606-fe5ad3339bb6.png)


I am not sure but some versions that might also be the error when there is nothing to translate (so no content was found) - but i am fairly sure we updated that to a better message.

**Comment by bielu** [comment]
@KevinJump I do
![image](https://user-images.githubusercontent.com/2244074/201916447-15b46950-d69c-4377-ad7f-220fb90f1ee1.png)
version 9.1.5

**Comment by KevinJump** [comment]
Umbraco version ?

**Comment by bielu** [comment]
V9

**Comment by KevinJump** [comment]
Hi, 

I get that error if i try to send a content page that does not vary by culture but is in a tree that does vary by culture to translation. 

e.g. In the screenshot below "Not Vary" does not vary by culture.

![image](https://user-images.githubusercontent.com/431231/201954280-08feee92-8567-48d5-a8e9-5e11d6af7388.png)

If i send it direct i get the same error you are seeing

if i send its parent, it all works, because at that level, it is excluded from translation. 

In this setup (non-varying items in a varying tree) those pages cannot be translated as there is nowhere to put the translated content. 

error could be nicer but i think that's the issue.

**Comment by bielu** [comment]
@KevinJump will check it and get back to you

**Comment by bielu** [comment]
@KevinJump can confirm it was an issue, Could we please get nice error message in in of future updates :)

**Comment by bielu** [comment]
@KevinJump follow up after trying play around with it
Okey it was working when i have 2 sets, but now when have configuration like this:
<img width="180" alt="image" src="https://user-images.githubusercontent.com/2244074/203041546-4a71b9a6-a5e5-4c7a-940c-855209523d29.png">
and for each of them I have configure source (once for each of languages) 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/2244074/203041668-628c7f2f-6d16-4b32-8196-8474bcd44c73.png">
I cannot publish with same error as on begging.
Also to make sure i skipped non vary elements by ignoring their document types
Do it wrong?

**Comment by bielu** [comment]
@KevinJump did you have maybe chance to look into it :)?

**Comment by KevinJump** [comment]
Hi yeah i need to play about with a configuration like this locally - everything is pointing at everything else ? 

I wouldn't actually recommend this setup the potential for tripping over your own translations is quite high (for example if you have a "En to all" translation and a "NL to ALL" translation both out at the same time, the way you reapply them will be quite important for you not to lose data in-between).

but i will have a look and see why it throws the errors.

**Comment by bielu** [comment]
@KevinJump we using it to copy content between countries :) so yeah each node can be translated to any language from any language

**Comment by KevinJump** [comment]
If the content doesn't actually change? have you considered using non-variant properties, so for example a product SKU is set only once, and all languages share it. 

In general people tend to have a master language they do all the work in and copy to all the others - its not that the above setup won't work, it just seems a little complex 🙂

**Comment by bielu** [comment]
@KevinJump content change between languages it is why we have that issue 😓

**Comment by KevinJump** [comment]
Sounds difficult 🙂 

anyway . i think you are actually getting this error ? 

![image](https://user-images.githubusercontent.com/431231/203520953-d35d60f0-8470-4dac-8e05-a26728b137d1.png)

Which will be because Translation manager is struggling to understand where the content node actually belongs. internally. we look for the translation sets based on the culture of the current node, and when you have a setup like above anyone 'target' node (that is the place we are translating too. is actually in multiple translation sets- so it is failing to work out. exactly where to put the content when it comes back.

I will take a look and see if its possible for us to work this out, but fair warning it might not be a simple/possible fix for us.

**Comment by bielu** [comment]
@KevinJump it is exactly this error :)

**Comment by KevinJump** [comment]
Hi, 

It wasn't super simple, but it was doable 🎉

we have a v9 nightly that will hopefully solve this problem: 

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/Jumoo.TranslationManager/overview/9.1.6-build.20221123.2

(see [connect to this feed](https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/connect/nuget.exe) for more info on how to get packages in your project - usually i do this with a custom nuget.config file in the root of the solution)

**Comment by bielu** [comment]
@KevinJump you already send few nightlies :) so I know what do to 😄 
will test it asap. :)

**Comment by bielu** [comment]
@KevinJump sadly same 
![image](https://user-images.githubusercontent.com/2244074/203579723-b75ef1e8-f119-4ecb-b6bb-38d08ff1c2d2.png)
![image](https://user-images.githubusercontent.com/2244074/203579865-7bb488d7-3092-450a-aa39-c61b1915ec05.png)

**Comment by bielu** [comment]
@KevinJump earlier I pulled wrong beta 😓 the latest build fix issue! :)

**Comment by KevinJump** [comment]
Woot ! - We are probibly going to release this v-soon, we need to get refreshed versions of everything out anyway. I will keep you posted.
