### ISSUE TITLE
"Send to Translation" creates job instead of adding to the pending queue

### ISSUE THREAD

**Issue by mayhammf** [Jumoo/Jumoo.TranslationManager.Issues#50]
### Description: 
It is not possible to add translation as pending. 

### Repro steps
- Right click on document 
- Click Send to translation 
#### Actual result: 
The UI initiate Job creation flow instead of just adding to pending.
#### Expected result: 
Translation item is added as the pending queue. 

### Environment: 
Translation Manager: v10.1.4.0
Global Configuration: 
```JSON
{
    "Translation": {
        "backgroundCheck": true,
        "checkPeriod": 180,
        "autoTranslate": false, // Notice autoTranslate is set to false.
        "includeEmpty": false,
        "batchSize": 25,
        "showHistory": true,
        "fixup": false,
        "returnToPending": false,
        "links": {
            "updatePicked": true,
            "updateInline": true
        },
        "notify": {
            "pending": "",
            "approved": "",
            "submitted": "",
            "received": ""
        },
        "tagSettings": {
            "tags": "img,a",
            "attributes": "title,alt"
        }
    }
}
```

Connector config: Default. 
Translation set config: 
![image](https://user-images.githubusercontent.com/5937658/231104251-4ea36d7a-d627-43b4-875b-367f47b2ff28.png)

**Comment by KevinJump** [comment]
Thanks, 

yeah this turns out is a quick one to fix, and it gives us an excuse to push out the latest release. 

fixed in v10.2.0 and v11.2.0

https://github.com/Jumoo/Jumoo.TranslationManager.Issues/releases/tag/v11.2.0
