### ISSUE TITLE
Not including all my properties, and the values are blank

### ISSUE THREAD

**Issue by david-ozum** [Jumoo/Jumoo.TranslationManager.Issues#52]
I think I have something fundamental wrong with my app. 

My Blog Post has properties including; title (textstring), description (textarea), and mainContent (RTE) (+ nodeName of course). All these properties vary by culture and were assigned through two different compositions.
![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/127974851/6108fa34-f83c-469f-9300-4f7043417b43)
![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/127974851/938965c2-a0c6-42b5-8a04-66992d1f16c4)
![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/127974851/92f1a9fa-4be3-4f0b-bbde-0adfed9e52b0)

When my blog post that has these properties populated, if shows 3 properties, and 0 words. I suspect the 3 includes nodeName.
![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/127974851/dc2308fa-20b6-4eb8-be85-45f9a0f92db6)

When I send the content for translation the mainContent property is missing entirely and the other two properties are blank. mainContent is set be a different composition, and is also on another tab from the other two properties.

My translation set has * for the property filter.
![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/127974851/58adf03b-7651-417f-8d6e-5b495b805678)

I'm at a bit of a loss to know where the issue might be.

![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/127974851/6d832692-f436-4bbe-bae3-285fea853c9b)

It is running on Umbraco v11, and upgraded from v8, so I don't know if some corruption could creep in there?

Could there be some temp files left on the server that might upset things?

**Comment by KevinJump** [comment]
Hi, 

It might be your source language, i notice on the screenshots, your content is in the "English" version of the page.
but the translation set it translating from English (United Kingdom) - 

I would change the master node for the set to use "English" as it appears in the drop down on the content page.

**Comment by david-ozum** [comment]
Yes - it is that. Language options changed and not updated in the translation set. Thank you.
