### ISSUE TITLE
Translation Stats for whole website

### ISSUE THREAD

**Issue by AndersBrohus** [Jumoo/Jumoo.TranslationManager.Issues#55]
Hi Kevin :)

We have a client which asks if it's possible to get the translations stats for the whole website, so they know the total word count and characters count :)

![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/9005889/9801ec58-1781-4df6-96b9-df79a3e9450b)

Is it somehow possible to get that? :)

**Comment by KevinJump** [comment]
Hi, 

From 10.3/11.3/12.3 you can do that, there is an additional count child pages option on that screen, 

![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/431231/03781337-9ca7-4d22-b3ca-c1dac965cf06)

It bascially does the same but for all children too (so from the homepage - its the whole site.

**Comment by KevinJump** [comment]
Also, while there isn't a v8 version - we have released some (unsupported) code to do this in v8 

https://gist.github.com/KevinJump/db21a4c6175352048baf4c203cf862bd

**Comment by AndersBrohus** [comment]
Thanks alot @KevinJump 🎉
