### ISSUE TITLE
Clone function not working in V13

### ISSUE THREAD

**Issue by gabador-mof** [Jumoo/Jumoo.TranslationManager.Issues#57]
Hi Kevin, 

I've seen one of your comments on a forum, where you mentioned using the clone function for creating a like for like structure of a page in another language, that is able to copy block list module content to other language variants. 

I've just installed translation manager into a site, and this is not working. It says content was cloned from en-US to ru, but I don't see any content, including page content. Am I doing something wrong? What's the configuration for making this work? 

Thanks for any assistance! 
Gabor

**Comment by KevinJump** [comment]
Hi, 

have you tried refreshing the page, on later versions of umbraco i think there is a bug where the page doesn't reload after the clone when it should. 

if not. what version of Umbraco are you running and we will siee if there is something we can find.

**Comment by gabador-mof** [comment]
Hi Kevin,

Yes, that fixes it! Thanks so much!

It might be good to refresh the page after the clone function in the
future.

Thanks again!
Gabor

**Comment by KevinJump** [comment]
this is fixed in v13.0.5/12.5.5/10.5.5 release (the page refreshes again).
