### ISSUE TITLE
Smidge error on SmartCat connector's settings page

### ISSUE THREAD

**Issue by krebil** [Jumoo/Jumoo.TranslationManager.Issues#58]
When I go to configure the smartcat connector I get the following error, which results in a blank page:

```
[15:22:13 ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: No such file exists /App_Plugins/Translations.Smartcat/smartcat.service.js?v=1 (mapped from /App_Plugins/Translations.Smartcat/smartcat.service.js?v=1)
File name: '/App_Plugins/Translations.Smartcat/smartcat.service.js?v=1'
   at Smidge.SmidgeFileSystem.GetRequiredFileInfo(IWebFile webfile)
   at Smidge.FileProcessors.PreProcessManager.<>c__DisplayClass8_0.<ProcessFileImpl>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

The file seems to be there: 
![image](https://github.com/Jumoo/Jumoo.TranslationManager.Issues/assets/1363512/be5112e1-fa54-41bb-afc1-2b49cb51f414)

**Comment by krebil** [comment]
I can't recreate on a fresh install, so I'll go ahead and close it for now

**Comment by krebil** [comment]
I have gone through the smidge preprocessor manager and there seems to be an issue with the v=1 part in the manifest file

`{
  "javascript": [
    "~/App_Plugins/Translations.Smartcat/smartcat.service.js?v=1",
    "~/App_Plugins/Translations.Smartcat/config.controller.js",
    "~/App_Plugins/Translations.Smartcat/pending.controller.js",
    "~/App_Plugins/Translations.Smartcat/submitted.controller.js"
  ],
  "css": [
    "~/App_Plugins/Translations.Smartcat/smartcat.css"
  ]
}`

If I remove that then it works again

**Comment by KevinJump** [comment]
Hi, 

yes, removed it for a new version (i think something changed recently in how Umbraco reads in the package files because this use to work as a way of breaking the cache.)

https://www.nuget.org/packages/Jumoo.TranslationManager.Smartcat/9.1.1
