### ISSUE TITLE
Error Create Job with OpenAi connector

### ISSUE THREAD

**Issue by FransdeJong** [Jumoo/Jumoo.TranslationManager.Issues#60]
I'm running into an error when using OpenAi connector.
It seems to go through all pages and error out when creating a job.

Translating a single page is successfull without errors.

The error has no details so I don't know where to start to solve this issue and if it's a translationmanager or a openAi connector issue...

<img width="484" alt="image" src="https://github.com/user-attachments/assets/a4a9d049-8e47-43b1-825d-b0d62d5e23a2">

<img width="1670" alt="image" src="https://github.com/user-attachments/assets/a4b3504a-6b76-4144-877b-148be9ac60bd">

**Comment by KevinJump** [comment]
Hi, 

can you see if there are any errors in the browser console/network tab ? (sometimes if JSON casing is changed the errors are there just not showing.)

**Comment by FransdeJong** [comment]
These are the errors I see in the console right now.

![image](https://github.com/user-attachments/assets/b3a11e6e-17e8-441b-87fa-6b687fda0876)

**Comment by FransdeJong** [comment]
@KevinJump 
This time around it logged a error. This is a rate limit error.

Strange that it didn't log it before...

So it seems rate limit errors aren't shown in the error details of translationmanager.

**Comment by KevinJump** [comment]
:( - yeah I will take a look, we should at least be telling you when you hit the limits.

**Comment by FransdeJong** [comment]
If it at least reliability logs the errors that's a good start.

**Comment by jdpnielsen** [comment]
I'm also experiencing issues with the OpenAI connector. I'm on a Umbraco v13.4.1 project with Jumoo.TranslationManager v13.1.3 & Jumoo.TranslationManager.OpenAi v1.0.0.

I get a slightly different error message though:

```
{
    "success": false,
    "result": null,
    "error": {
        "title": "Error submitting job",
        "message": "Object reference not set to an instance of an object.",
        "className": "<TranslateLegacy>d__8",
        "method": "MoveNext",
        "stackTrace": 
           at Jumoo.TranslationManager.OpenAi.Services.BetalgoOpenAiService.TranslateLegacy(List`1 text, OpenAITranslationOptions translationOptions)
           at Jumoo.TranslationManager.OpenAi.Services.BetalgoOpenAiService.Translate(List`1 text, OpenAITranslationOptions translationOptions)
           at Jumoo.TranslationManager.OpenAi.OpenAiConnector.TranslateStringValues(IEnumerable`1 values, String sourceLang, String targetLang, Boolean isHtml)
           at Jumoo.TranslationManager.OpenAi.OpenAiConnector.TranslateStringValue(String source, String sourceLang, String targetLang)
           at Jumoo.TranslationManager.OpenAi.OpenAiConnector.GetTranslatedValue(TranslationValue source, TranslationValue target, String sourceLang, String targetLang)
           at Jumoo.TranslationManager.OpenAi.OpenAiConnector.Submit(TranslationJob job)
           at Jumoo.TranslationManager.Core.Services.TranslationJobService.SubmitJob(TranslationJob job)
           at Jumoo.TranslationManager.Core.Controllers.TranslationJobApiController.Submit(Int32 id)
    }
}
```

Payload was:

```
{
  "name": "English (United States) - 19/07/2024, 12:30",
  "nodes": [
    {
      "setKey": "f7fd8a18-e4b2-48ff-8dbd-11232a993982",
      "culture": {
        "id": 1033,
        "name": "en-US",
        "displayName": "English (United States)",
        "twoLetterISOLanguageName": "en",
        "threeLetterISOLanguageName": "eng",
        "threeLetterWindowsLanguageName": "ENU"
      },
      "masterNodeId": 1445,
      "targetNodeId": 1445,
      "status": "Open",
      "created": "2024-07-19T12:30:01.652058",
      "updated": "2024-07-19T12:30:19.065356Z",
      "masterNodeName": "Det her er sket! - Breaking breaking",
      "targetNodeName": "Det her er sket! - Breaking breaking",
      "masterNodePath": null,
      "targetNodePath": null,
      "isDictionary": false,
      "contentVersionId": 467,
      "targetVersionId": 0,
      "groups": [],
      "hasOpenSiblings": false,
      "targetNodePermissions": null,
      "key": "72e1854a-2584-42d2-a62a-f96d9bbdf7c5",
      "id": 4
    }
  ],
  "providerKey": "d60c3b07-2fce-4568-8a1d-c3286a73df8a",
  "providerOptions": {},
  "autoApprove": false,
  "replaceNodeName": false,
  "clientId": "",
  "groupId": "d26e45fc-a228-4a68-ac56-448c3d79f5e4"
}
```

**Comment by KevinJump** [comment]
Hi, 

looks like its a bit of ever-chaning api (some of the models where deprecated). 

We have updated for both these issues, so hopefully v1.0.1 will have better error logging and won't throw the null error when using some of the older models. 

https://www.nuget.org/packages/Jumoo.TranslationManager.OpenAi/1.0.1

**Comment by jdpnielsen** [comment]
@KevinJump Thanks for the quick update! Can confirm this resolved our issue!
