### ISSUE TITLE
Xliff file connector not saving to blob storage

### ISSUE THREAD

**Issue by TheBekker** [Jumoo/Jumoo.TranslationManager.Issues#9]
Currently working on a customer solution that uses blob storage, and are considering TM for translation of their sites.
Though while testing, I noticed that Xliff files are not ending up in blob storage, but instead on disk, which is kind of a deal breaker.

I see there was an old forum post regarding this back in 2019, what is the status of this?
https://our.umbraco.com/packages/backoffice-extensions/translation-manager/translation-manager-feedback/95420-umbraco-file-system-provider-not-working-with-xliff-file-provider

**Comment by KevinJump** [comment]
I am fairly sure we did do something on Umbraco v7, but i am not sure if we had the same solution for v8 - i will take a look.

**Comment by TheBekker** [comment]
> I am fairly sure we did do something on Umbraco v7, but i am not sure if we had the same solution for v8 - i will take a look.

Any news on this one? :)

**Comment by KevinJump** [comment]
Hi, we have finally fixed it ! - v8.7.0 supports the blob storage. 

https://github.com/Jumoo/Jumoo.TranslationManager.Issues/releases/tag/8.7.0

**Comment by TheBekker** [comment]
So awesome!
Looking forward to testing it!
